name: Practical 13 CI/CD Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


permissions:
  contents: read
  packages: write


jobs:

  build-and-publish:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - name: Install Student Service Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r student-service/requirements.txt

      - name: Install Course Service Dependencies
        run: |
          pip install -r course-service/requirements.txt

      - name: Install API Gateway Dependencies
        run: |
          pip install -r api-gateway/requirements.txt

      - name: Check Python Files
        run: |
          python -m py_compile student-service/app/main.py
          python -m py_compile course-service/app/main.py
          python -m py_compile api-gateway/app/main.py

      - name: Build Docker Images
        run: |
          docker compose build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag Docker Images
        run: |
          docker tag practical_12-student-service:latest ghcr.io/${{ github.repository_owner }}/practical-12-student-service:latest
          docker tag practical_12-course-service:latest ghcr.io/${{ github.repository_owner }}/practical-12-course-service:latest
          docker tag practical_12-api-gateway:latest ghcr.io/${{ github.repository_owner }}/practical-12-api-gateway:latest

      - name: Push Docker Images
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/practical-12-student-service:latest
          docker push ghcr.io/${{ github.repository_owner }}/practical-12-course-service:latest
          docker push ghcr.io/${{ github.repository_owner }}/practical-12-api-gateway:latest

      - name: CI/CD Pipeline Successful
        run: echo "CI/CD pipeline completed successfully"